### PR TITLE
fixes #835 escaped binary data in collision logging

### LINKED ISSUE #835: Collision trace logging does not hex escape data
While trying to debug some unexpected collisions in webindex, I noticed that logging of collisions does not hex escape binary data like other transaction trace logging does.
```
17:48:45.466 [Fluo-0002-007-async-commits] TRACE fluo.tx.collisions - txid: 14580734 trigger: p:1prp:net.analystratings>.www>o>/stocks/NYSE/LCI/ page new  14536153
17:48:45.466 [Fluo-0002-007-async-commits] TRACE fluo.tx.collisions - txid: 14580734 class: webindex.data.fluo.PageObserver
17:48:45.466 [Fluo-0002-007-async-commits] TRACE fluo.tx.collisions - txid: 14580734 collisions: {um:u:679:^C^Acom.reuters>.www>o>/finance/stocks/companyProfile?symbol=LC�^@^@^@^@^@�{�=[u v ], um:u:366:^C^A�^Agov.sec>.www>o>/Archives/edgar/data/57725/000120919115012121/xslF345X03/doc4.xml^@^@^@^@^@�{�=[u v ]}
```

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: modules/core/src/main/java/org/apache/fluo/core/log/TracingTransaction.java [hunk 1]
```diff
@@ -96,6 +96,11 @@ private String encC(Map<Column, Bytes> ret) {
         + "=" + enc(e.getValue())));
   }
 
+  private String encMBC(Map<Bytes, Set<Column>> m) {
```
Comment (ctubbsii) [inline modules/core/src/main/java/org/apache/fluo/core/log/TracingTransaction.java]: New private method with obfuscated name should have some comment describing what it's supposed to do.

File: modules/integration/src/test/java/org/apache/fluo/integration/TestUtil.java [hunk 2]
```diff
@@ -17,18 +17,26 @@
...
 
 public class TestUtil {
 
   private TestUtil() {}
 
+  private static final Bytes ZERO = Bytes.of("0");
+
+  public static void increment(TransactionBase tx, Bytes row, Column col, int val) {
+    int prev = 0;
+    String prevStr = tx.get(row, col, ZERO).toString();
```
Comment (ctubbsii) [inline modules/integration/src/test/java/org/apache/fluo/integration/TestUtil.java]: Is it safe to call toString here on arbitrary bytes?

Comment (keith-turner) [inline modules/integration/src/test/java/org/apache/fluo/integration/TestUtil.java]: I think its safe since its internal test code and we have full control over all of the code that calls it.

File: modules/core/src/main/java/org/apache/fluo/core/log/TracingTransaction.java (hunk 1 above)
Comment (keith-turner) [inline modules/core/src/main/java/org/apache/fluo/core/log/TracingTransaction.java]: A better method name would help also.  Maybe `toEscapedString(...)`

Comment (keith-turner) [inline modules/core/src/main/java/org/apache/fluo/core/log/TracingTransaction.java]: I changed the method names.  I didn't think comments were needed since the methods are private, have descriptive name, and are single line implementations.
