### PR TITLE
Fixes #818 - Old/new observers config exception is causing ITs to fail

### LINKED ISSUE #818: Old/new observers config exception is causing ITs to fail
Multiple ITs are failing due to exception. It looks like this was caused by #817.

```
org.apache.fluo.api.exceptions.FluoException: Failed to update shared configuration in Zookeeper
Caused by: java.lang.IllegalArgumentException: Old and new observers configuration present.  There can only be one.
```

### PR DESCRIPTION
**Pull request by mikewalch**
* Fixed bug and created unit test to verify

### CODE REVIEW

File: modules/api/src/main/java/org/apache/fluo/api/config/FluoConfiguration.java [hunk 1]
```diff
@@ -306,7 +306,8 @@ public int getWorkerThreads() {
 
     while (iter.hasNext()) {
       String key = iter.next();
-      if (key.startsWith(FluoConfiguration.OBSERVER_PREFIX)) {
+      if (!key.startsWith(FluoConfiguration.OBSERVER_PROVIDER)
```
Comment (keith-turner) [inline modules/api/src/main/java/org/apache/fluo/api/config/FluoConfiguration.java]: could do not equals OBSERVER_PROVIDER

Comment (mikewalch) [inline modules/api/src/main/java/org/apache/fluo/api/config/FluoConfiguration.java]: fixed with latest commit
